In [29]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [30]:
df=pd.read_csv("C:/Users/Najeeb ULLAH/Downloads/Bank-Customer-Attrition-Insights-Data.csv")

In [31]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,1,15598695,Fields,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464
1,2,15649354,Johnston,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
2,3,15737556,Vasilyev,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377
3,4,15671610,Hooper,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350
4,5,15625092,Colombo,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15583480,Morgan,771,France,Male,39,5,0.00,2,1,0,96270.64,0,0,1,DIAMOND,300
9996,9997,15620341,Nwebube,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,0,5,PLATINUM,771
9997,9998,15613886,Trevisan,709,France,Female,36,7,0.00,1,0,1,42085.58,1,1,3,SILVER,564
9998,9999,15792916,Ositadimma,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,1,2,GOLD,339
9999,10000,15710408,Cunningham,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,0,3,DIAMOND,911

In [32]:
cols = df.select_dtypes(include=['object']).columns

label_encoders = {}  
for col in cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [33]:
y=df['Complain']

In [34]:
df.drop('Complain',axis=1,inplace=True)

In [35]:
X=df

In [36]:
X

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Satisfaction Score,Card Type,Point Earned
0,1,15598695,882,619,0,0,42,2,0.00,1,1,1,101348.88,1,2,0,464
1,2,15649354,1335,608,2,0,41,1,83807.86,1,0,1,112542.58,0,3,0,456
2,3,15737556,2714,502,0,0,42,8,159660.80,3,1,0,113931.57,1,3,0,377
3,4,15671610,1203,699,0,0,39,1,0.00,2,0,0,93826.63,0,5,1,350
4,5,15625092,595,850,2,0,43,2,125510.82,1,1,1,79084.10,0,5,1,425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15583480,1849,771,0,1,39,5,0.00,2,1,0,96270.64,0,1,0,300
9996,9997,15620341,1974,516,0,1,35,10,57369.61,1,1,1,101699.77,0,5,2,771
9997,9998,15613886,2644,709,0,0,36,7,0.00,1,0,1,42085.58,1,3,3,564
9998,9999,15792916,2069,772,1,1,42,3,75075.31,2,1,0,92888.52,1,2,1,339
9999,10000,15710408,651,792,0,0,28,4,130142.79,1,1,0,38190.78,0,3,0,911

In [40]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2)

In [41]:
Lg=LogisticRegression()

In [42]:
Lg.fit(Xtrain,ytrain)

C:\Users\Najeeb ULLAH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [43]:
Lg.predict(Xtest)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [44]:
classification_report(ytest,Lg.predict(Xtest))

C:\Users\Najeeb ULLAH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Najeeb ULLAH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Najeeb ULLAH\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

'              precision    recall  f1-score   support\n\n           0       0.80      1.00      0.89      1602\n           1       0.00      0.00      0.00       398\n\n    accuracy                           0.80      2000\n   macro avg       0.40      0.50      0.44      2000\nweighted avg       0.64      0.80      0.71      2000\n'